package com.maskmanage.mapper;

import com.maskmanage.entity.column;
import com.maskmanage.entity.columnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface columnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int countByExample(columnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int deleteByExample(columnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int deleteByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int insert(column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int insertSelective(column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    List<column> selectByExample(columnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    column selectByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") column record, @Param("example") columnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int updateByExample(@Param("record") column record, @Param("example") columnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int updateByPrimaryKeySelective(column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table column
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    int updateByPrimaryKey(column record);
}