package com.maskmanage.mapper;

import com.maskmanage.entity.maskusage;
import com.maskmanage.entity.maskusageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface maskusageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int countByExample(maskusageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByExample(maskusageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByPrimaryKey(Integer usageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insert(maskusage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insertSelective(maskusage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    List<maskusage> selectByExample(maskusageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    maskusage selectByPrimaryKey(Integer usageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") maskusage record, @Param("example") maskusageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExample(@Param("record") maskusage record, @Param("example") maskusageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKeySelective(maskusage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskusage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKey(maskusage record);
}