package com.maskmanage.mapper;

import com.maskmanage.entity.maskstorage;
import com.maskmanage.entity.maskstorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface maskstorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int countByExample(maskstorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByExample(maskstorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByPrimaryKey(Integer storageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insert(maskstorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insertSelective(maskstorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    List<maskstorage> selectByExample(maskstorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    maskstorage selectByPrimaryKey(Integer storageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") maskstorage record, @Param("example") maskstorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExample(@Param("record") maskstorage record, @Param("example") maskstorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKeySelective(maskstorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskstorage
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKey(maskstorage record);
}