package com.maskmanage.mapper;

import com.maskmanage.entity.maskadmin;
import com.maskmanage.entity.maskadminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface maskadminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int countByExample(maskadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByExample(maskadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insert(maskadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insertSelective(maskadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    List<maskadmin> selectByExample(maskadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    maskadmin selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") maskadmin record, @Param("example") maskadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExample(@Param("record") maskadmin record, @Param("example") maskadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKeySelective(maskadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskadmin
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKey(maskadmin record);
}