package com.maskmanage.mapper;

import com.maskmanage.entity.maskuser;
import com.maskmanage.entity.maskuserExample;
import com.maskmanage.entity.maskuserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface maskuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int countByExample(maskuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByExample(maskuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByPrimaryKey(maskuserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insert(maskuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insertSelective(maskuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    List<maskuser> selectByExample(maskuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    maskuser selectByPrimaryKey(maskuserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") maskuser record, @Param("example") maskuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExample(@Param("record") maskuser record, @Param("example") maskuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKeySelective(maskuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskuser
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKey(maskuser record);
}