package com.maskmanage.mapper;

import com.maskmanage.entity.maskcolumn;
import com.maskmanage.entity.maskcolumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface maskcolumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int countByExample(maskcolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByExample(maskcolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int deleteByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insert(maskcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int insertSelective(maskcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    List<maskcolumn> selectByExample(maskcolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    maskcolumn selectByPrimaryKey(Integer columnid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") maskcolumn record, @Param("example") maskcolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByExample(@Param("record") maskcolumn record, @Param("example") maskcolumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKeySelective(maskcolumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maskcolumn
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    int updateByPrimaryKey(maskcolumn record);
}