package com.maskmanage.mapper;

import com.maskmanage.entity.resource;
import com.maskmanage.entity.resourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface resourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int countByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int deleteByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int deleteByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int insert(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int insertSelective(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    List<resource> selectByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    resource selectByPrimaryKey(Integer resid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") resource record, @Param("example") resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int updateByExample(@Param("record") resource record, @Param("example") resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int updateByPrimaryKeySelective(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    int updateByPrimaryKey(resource record);
}