package com.maskmanage.entity;

import java.util.Date;

public class donation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.donationId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer donationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.donationName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String donationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.resourceId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.donationAmount
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String donationamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.fromDonatorId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer fromdonatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.donationTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Date donationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.donationId
     *
     * @return the value of donation.donationId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getDonationid() {
        return donationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.donationId
     *
     * @param donationid the value for donation.donationId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDonationid(Integer donationid) {
        this.donationid = donationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.donationName
     *
     * @return the value of donation.donationName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getDonationname() {
        return donationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.donationName
     *
     * @param donationname the value for donation.donationName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDonationname(String donationname) {
        this.donationname = donationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.resourceId
     *
     * @return the value of donation.resourceId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.resourceId
     *
     * @param resourceid the value for donation.resourceId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.donationAmount
     *
     * @return the value of donation.donationAmount
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getDonationamount() {
        return donationamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.donationAmount
     *
     * @param donationamount the value for donation.donationAmount
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDonationamount(String donationamount) {
        this.donationamount = donationamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.fromDonatorId
     *
     * @return the value of donation.fromDonatorId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getFromdonatorid() {
        return fromdonatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.fromDonatorId
     *
     * @param fromdonatorid the value for donation.fromDonatorId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setFromdonatorid(Integer fromdonatorid) {
        this.fromdonatorid = fromdonatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.donationTime
     *
     * @return the value of donation.donationTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Date getDonationtime() {
        return donationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.donationTime
     *
     * @param donationtime the value for donation.donationTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDonationtime(Date donationtime) {
        this.donationtime = donationtime;
    }
}