package com.maskmanage.entity;

public class express {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.expressId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private Integer expressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.expressTitle
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private String expresstitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.type
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.amount
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.expressApi
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private String expressapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.reqrId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    private Integer reqrid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.expressId
     *
     * @return the value of express.expressId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public Integer getExpressid() {
        return expressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.expressId
     *
     * @param expressid the value for express.expressId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setExpressid(Integer expressid) {
        this.expressid = expressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.expressTitle
     *
     * @return the value of express.expressTitle
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public String getExpresstitle() {
        return expresstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.expressTitle
     *
     * @param expresstitle the value for express.expressTitle
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setExpresstitle(String expresstitle) {
        this.expresstitle = expresstitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.type
     *
     * @return the value of express.type
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.type
     *
     * @param type the value for express.type
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.amount
     *
     * @return the value of express.amount
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.amount
     *
     * @param amount the value for express.amount
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.expressApi
     *
     * @return the value of express.expressApi
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public String getExpressapi() {
        return expressapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.expressApi
     *
     * @param expressapi the value for express.expressApi
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setExpressapi(String expressapi) {
        this.expressapi = expressapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.reqrId
     *
     * @return the value of express.reqrId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public Integer getReqrid() {
        return reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.reqrId
     *
     * @param reqrid the value for express.reqrId
     *
     * @mbggenerated Fri May 29 11:02:06 CST 2020
     */
    public void setReqrid(Integer reqrid) {
        this.reqrid = reqrid;
    }
}