package com.maskmanage.entity;

import java.util.Date;

public class maskstorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskstorage.storageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer storageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskstorage.hosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer hosid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskstorage.resId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskstorage.storageNum
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer storagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskstorage.updateTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskstorage.storageId
     *
     * @return the value of maskstorage.storageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskstorage.storageId
     *
     * @param storageid the value for maskstorage.storageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setStorageid(Integer storageid) {
        this.storageid = storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskstorage.hosId
     *
     * @return the value of maskstorage.hosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getHosid() {
        return hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskstorage.hosId
     *
     * @param hosid the value for maskstorage.hosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setHosid(Integer hosid) {
        this.hosid = hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskstorage.resId
     *
     * @return the value of maskstorage.resId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskstorage.resId
     *
     * @param resid the value for maskstorage.resId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskstorage.storageNum
     *
     * @return the value of maskstorage.storageNum
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getStoragenum() {
        return storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskstorage.storageNum
     *
     * @param storagenum the value for maskstorage.storageNum
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setStoragenum(Integer storagenum) {
        this.storagenum = storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskstorage.updateTime
     *
     * @return the value of maskstorage.updateTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskstorage.updateTime
     *
     * @param updatetime the value for maskstorage.updateTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}