package com.maskmanage.entity;

import java.util.Date;

public class maskdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskdata.dataId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskdata.dataTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String datatitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskdata.dataLocation
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String datalocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskdata.dataAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer dataadminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskdata.dataPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Date datapubtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskdata.dataId
     *
     * @return the value of maskdata.dataId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskdata.dataId
     *
     * @param dataid the value for maskdata.dataId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDataid(Integer dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskdata.dataTitle
     *
     * @return the value of maskdata.dataTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getDatatitle() {
        return datatitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskdata.dataTitle
     *
     * @param datatitle the value for maskdata.dataTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDatatitle(String datatitle) {
        this.datatitle = datatitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskdata.dataLocation
     *
     * @return the value of maskdata.dataLocation
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getDatalocation() {
        return datalocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskdata.dataLocation
     *
     * @param datalocation the value for maskdata.dataLocation
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDatalocation(String datalocation) {
        this.datalocation = datalocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskdata.dataAdminId
     *
     * @return the value of maskdata.dataAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getDataadminid() {
        return dataadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskdata.dataAdminId
     *
     * @param dataadminid the value for maskdata.dataAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDataadminid(Integer dataadminid) {
        this.dataadminid = dataadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskdata.dataPubTime
     *
     * @return the value of maskdata.dataPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Date getDatapubtime() {
        return datapubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskdata.dataPubTime
     *
     * @param datapubtime the value for maskdata.dataPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setDatapubtime(Date datapubtime) {
        this.datapubtime = datapubtime;
    }
}