package com.maskmanage.entity;

public class maskusage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.usageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer usageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.usageTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String usagetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer reqrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.usageDesc
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String usagedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.usageStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer usagestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskusage.usageHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer usagehosid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.usageId
     *
     * @return the value of maskusage.usageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getUsageid() {
        return usageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.usageId
     *
     * @param usageid the value for maskusage.usageId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsageid(Integer usageid) {
        this.usageid = usageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.usageTitle
     *
     * @return the value of maskusage.usageTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUsagetitle() {
        return usagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.usageTitle
     *
     * @param usagetitle the value for maskusage.usageTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsagetitle(String usagetitle) {
        this.usagetitle = usagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.reqrId
     *
     * @return the value of maskusage.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getReqrid() {
        return reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.reqrId
     *
     * @param reqrid the value for maskusage.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrid(Integer reqrid) {
        this.reqrid = reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.usageDesc
     *
     * @return the value of maskusage.usageDesc
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUsagedesc() {
        return usagedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.usageDesc
     *
     * @param usagedesc the value for maskusage.usageDesc
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsagedesc(String usagedesc) {
        this.usagedesc = usagedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.usageStatus
     *
     * @return the value of maskusage.usageStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getUsagestatus() {
        return usagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.usageStatus
     *
     * @param usagestatus the value for maskusage.usageStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsagestatus(Integer usagestatus) {
        this.usagestatus = usagestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskusage.usageHosId
     *
     * @return the value of maskusage.usageHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getUsagehosid() {
        return usagehosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskusage.usageHosId
     *
     * @param usagehosid the value for maskusage.usageHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsagehosid(Integer usagehosid) {
        this.usagehosid = usagehosid;
    }
}