package com.maskmanage.entity;

public class maskuserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskuser.userid
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskuser.username
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskuser.userid
     *
     * @return the value of maskuser.userid
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskuser.userid
     *
     * @param userid the value for maskuser.userid
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskuser.username
     *
     * @return the value of maskuser.username
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskuser.username
     *
     * @param username the value for maskuser.username
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }
}