package com.maskmanage.entity;

public class maskadmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskadmin.adminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskadmin.adminUserId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer adminuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskadmin.adminStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String adminstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskadmin.adminId
     *
     * @return the value of maskadmin.adminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskadmin.adminId
     *
     * @param adminid the value for maskadmin.adminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskadmin.adminUserId
     *
     * @return the value of maskadmin.adminUserId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getAdminuserid() {
        return adminuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskadmin.adminUserId
     *
     * @param adminuserid the value for maskadmin.adminUserId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setAdminuserid(Integer adminuserid) {
        this.adminuserid = adminuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskadmin.adminStatus
     *
     * @return the value of maskadmin.adminStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getAdminstatus() {
        return adminstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskadmin.adminStatus
     *
     * @param adminstatus the value for maskadmin.adminStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setAdminstatus(String adminstatus) {
        this.adminstatus = adminstatus;
    }
}