package com.maskmanage.entity;

import java.util.Date;

public class maskcolumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer columnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String columntitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.colAuthor
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String colauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer columnadminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnContent
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String columncontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnInterviewee
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String columninterviewee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskcolumn.columnPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Date columnpubtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnId
     *
     * @return the value of maskcolumn.columnId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnId
     *
     * @param columnid the value for maskcolumn.columnId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnTitle
     *
     * @return the value of maskcolumn.columnTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getColumntitle() {
        return columntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnTitle
     *
     * @param columntitle the value for maskcolumn.columnTitle
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumntitle(String columntitle) {
        this.columntitle = columntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.colAuthor
     *
     * @return the value of maskcolumn.colAuthor
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getColauthor() {
        return colauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.colAuthor
     *
     * @param colauthor the value for maskcolumn.colAuthor
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColauthor(String colauthor) {
        this.colauthor = colauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnAdminId
     *
     * @return the value of maskcolumn.columnAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getColumnadminid() {
        return columnadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnAdminId
     *
     * @param columnadminid the value for maskcolumn.columnAdminId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumnadminid(Integer columnadminid) {
        this.columnadminid = columnadminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnContent
     *
     * @return the value of maskcolumn.columnContent
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getColumncontent() {
        return columncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnContent
     *
     * @param columncontent the value for maskcolumn.columnContent
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumncontent(String columncontent) {
        this.columncontent = columncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnInterviewee
     *
     * @return the value of maskcolumn.columnInterviewee
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getColumninterviewee() {
        return columninterviewee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnInterviewee
     *
     * @param columninterviewee the value for maskcolumn.columnInterviewee
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumninterviewee(String columninterviewee) {
        this.columninterviewee = columninterviewee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskcolumn.columnPubTime
     *
     * @return the value of maskcolumn.columnPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Date getColumnpubtime() {
        return columnpubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskcolumn.columnPubTime
     *
     * @param columnpubtime the value for maskcolumn.columnPubTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setColumnpubtime(Date columnpubtime) {
        this.columnpubtime = columnpubtime;
    }
}