package com.maskmanage.entity;

public class maskuser extends maskuserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskuser.userRole
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String userrole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskuser.userPassword
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maskuser.userEmail
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String useremail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskuser.userRole
     *
     * @return the value of maskuser.userRole
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUserrole() {
        return userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskuser.userRole
     *
     * @param userrole the value for maskuser.userRole
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUserrole(String userrole) {
        this.userrole = userrole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskuser.userPassword
     *
     * @return the value of maskuser.userPassword
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskuser.userPassword
     *
     * @param userpassword the value for maskuser.userPassword
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maskuser.userEmail
     *
     * @return the value of maskuser.userEmail
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maskuser.userEmail
     *
     * @param useremail the value for maskuser.userEmail
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }
}