package com.maskmanage.entity;

import java.util.Date;

public class requirement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer reqrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String reqrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqType
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer reqtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Date reqrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer reqrstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqrHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private Integer reqrhosid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column requirement.reqStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    private String reqstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrId
     *
     * @return the value of requirement.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getReqrid() {
        return reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrId
     *
     * @param reqrid the value for requirement.reqrId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrid(Integer reqrid) {
        this.reqrid = reqrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrName
     *
     * @return the value of requirement.reqrName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getReqrname() {
        return reqrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrName
     *
     * @param reqrname the value for requirement.reqrName
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrname(String reqrname) {
        this.reqrname = reqrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqType
     *
     * @return the value of requirement.reqType
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getReqtype() {
        return reqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqType
     *
     * @param reqtype the value for requirement.reqType
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqtype(Integer reqtype) {
        this.reqtype = reqtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrTime
     *
     * @return the value of requirement.reqrTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Date getReqrtime() {
        return reqrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrTime
     *
     * @param reqrtime the value for requirement.reqrTime
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrtime(Date reqrtime) {
        this.reqrtime = reqrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrStatus
     *
     * @return the value of requirement.reqrStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getReqrstatus() {
        return reqrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrStatus
     *
     * @param reqrstatus the value for requirement.reqrStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrstatus(Integer reqrstatus) {
        this.reqrstatus = reqrstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqrHosId
     *
     * @return the value of requirement.reqrHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public Integer getReqrhosid() {
        return reqrhosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqrHosId
     *
     * @param reqrhosid the value for requirement.reqrHosId
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqrhosid(Integer reqrhosid) {
        this.reqrhosid = reqrhosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column requirement.reqStatus
     *
     * @return the value of requirement.reqStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public String getReqstatus() {
        return reqstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column requirement.reqStatus
     *
     * @param reqstatus the value for requirement.reqStatus
     *
     * @mbggenerated Sat May 30 19:20:01 CST 2020
     */
    public void setReqstatus(String reqstatus) {
        this.reqstatus = reqstatus;
    }
}