package com.maskmanage.entity;

import java.util.Date;

public class storage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storageId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    private Integer storageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.hosId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    private Integer hosid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.resId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    private Integer resid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.storageNum
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    private Integer storagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storage.updateTime
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storageId
     *
     * @return the value of storage.storageId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public Integer getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storageId
     *
     * @param storageid the value for storage.storageId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public void setStorageid(Integer storageid) {
        this.storageid = storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.hosId
     *
     * @return the value of storage.hosId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public Integer getHosid() {
        return hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.hosId
     *
     * @param hosid the value for storage.hosId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public void setHosid(Integer hosid) {
        this.hosid = hosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.resId
     *
     * @return the value of storage.resId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public Integer getResid() {
        return resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.resId
     *
     * @param resid the value for storage.resId
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public void setResid(Integer resid) {
        this.resid = resid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.storageNum
     *
     * @return the value of storage.storageNum
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public Integer getStoragenum() {
        return storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.storageNum
     *
     * @param storagenum the value for storage.storageNum
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public void setStoragenum(Integer storagenum) {
        this.storagenum = storagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storage.updateTime
     *
     * @return the value of storage.updateTime
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storage.updateTime
     *
     * @param updatetime the value for storage.updateTime
     *
     * @mbggenerated Sat May 30 09:44:25 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}